const $=s=>document.querySelector(s),home=$('#home'),chat=$('#chat'),routeScreen=$('#route'),messages=$('#messages'),voicePanel=$('#voicePanel'),detailSheet=$('#detailSheet'),transcript=$('#voiceTranscript'),input=$('#chatInput');
function toggleInputMode(forceText){const composer=$('#chatComposer'),text=typeof forceText==='boolean'?forceText:!composer.classList.contains('text-mode');composer.classList.toggle('text-mode',text);composer.classList.toggle('voice-mode',!text);const toggle=$('#inputModeToggle');toggle.textContent=text?'◉':'⌨';toggle.setAttribute('aria-label',text?'切换为语音输入':'切换为文字输入');if(text)setTimeout(()=>input.focus(),50)}
function toggleMorePanel(force){const panel=$('#morePanel'),open=typeof force==='boolean'?force:!panel.classList.contains('open');panel.classList.toggle('open',open);panel.setAttribute('aria-hidden',String(!open))}
function updateSideMenuLabels(){const menu=$('#sideMenu');if(!menu)return;menu.querySelector(':scope>header b').textContent='应用及对话';menu.querySelector(':scope>section h3').textContent='我的应用';const poi=[...menu.querySelectorAll('.business-apps b')].find(x=>x.textContent==='POI查询');if(poi)poi.textContent='周边查询'}
updateSideMenuLabels();
function closeHistoryDeletePrompt(){const prompt=$('#historyDeletePrompt');if(prompt)prompt.remove()}
function showHistoryDeletePrompt(item){closeHistoryDeletePrompt();const title=item.querySelector('b')?.textContent||'该会话';const prompt=document.createElement('div');prompt.id='historyDeletePrompt';prompt.className='history-delete-prompt';prompt.innerHTML=`<div><span>删除历史会话</span><b>${esc(title)}</b><p>删除后无法恢复，是否继续？</p><footer><button type="button" data-cancel-delete>取消</button><button type="button" class="danger" data-confirm-delete>删除</button></footer></div>`;$('#sideMenu').append(prompt);prompt.querySelector('[data-cancel-delete]').onclick=closeHistoryDeletePrompt;prompt.querySelector('[data-confirm-delete]').onclick=()=>{item.remove();closeHistoryDeletePrompt();toast('历史会话已删除')}}
function enableHistoryLongPress(){document.querySelectorAll('.history-list>button').forEach(item=>{let timer,startX=0,startY=0;item.addEventListener('pointerdown',event=>{startX=event.clientX;startY=event.clientY;timer=setTimeout(()=>{item.dataset.longPressed='1';navigator.vibrate?.(35);showHistoryDeletePrompt(item)},650)});item.addEventListener('pointermove',event=>{if(Math.abs(event.clientX-startX)>10||Math.abs(event.clientY-startY)>10){clearTimeout(timer)}});['pointerup','pointercancel','pointerleave'].forEach(type=>item.addEventListener(type,()=>clearTimeout(timer)));item.addEventListener('click',event=>{if(item.dataset.longPressed){event.preventDefault();event.stopImmediatePropagation();delete item.dataset.longPressed}},true);item.addEventListener('contextmenu',event=>event.preventDefault())})}
enableHistoryLongPress();
$('#cupWater').dataset.amount='400ml';
$('.water-hero>span').insertAdjacentHTML('afterend','<aside id="waterGoalBadge" class="water-goal-badge" aria-live="polite"><i>✓</i><b>今日饮水已达标</b></aside>');
let visibleWaterRecords=10;
$('#waterRecords').insertAdjacentHTML('afterend','<button id="loadMoreWaterRecords" class="water-load-more" onclick="loadMoreWaterRecords()">查看更多记录</button>');
function waterDateTime(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')} ${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`}
$('#waterRecords').querySelectorAll('time').forEach(time=>{time.textContent=`${waterDateTime().slice(0,10)} ${time.textContent}`});
function updateWaterRecordList(){const records=[...$('#waterRecords').children];records.forEach((record,index)=>record.classList.toggle('water-record-hidden',index>=visibleWaterRecords));const more=$('#loadMoreWaterRecords');more.hidden=records.length<=visibleWaterRecords;more.textContent=`查看更多记录${more.hidden?'':`（剩余 ${records.length-visibleWaterRecords} 条）`}`}
function loadMoreWaterRecords(){visibleWaterRecords+=10;updateWaterRecordList()}
updateWaterRecordList();
let autoReadEnabled=false;
function toggleAutoRead(){autoReadEnabled=!autoReadEnabled;const button=$('#autoReadButton');button.classList.toggle('active',autoReadEnabled);button.setAttribute('aria-pressed',String(autoReadEnabled));button.setAttribute('aria-label',autoReadEnabled?'关闭自动朗读':'开启自动朗读');if(!autoReadEnabled&&'speechSynthesis'in window)window.speechSynthesis.cancel();toast(autoReadEnabled?'已开启自动朗读':'已关闭自动朗读')}
function speakAgent(text){if(!autoReadEnabled||!('speechSynthesis'in window)||!text)return;window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(text);speech.lang='zh-CN';speech.rate=1;window.speechSynthesis.speak(speech)}
const CONFIG={ticketUrl:'https://www.whdonghu.gov.cn/',insuranceUrl:'https://www.picc.com/',amapBase:'https://uri.amap.com/navigation',updatedAt:'15:08'};
const DB={
 activity:{title:'2026跳东湖夏日派对',date:'2026年9月4—6日',time:'15:00—22:30',place:'东湖磨山景区楚城—滑道广场',hosts:'武汉东湖文旅（集团）有限公司',features:['水上娱乐','主题市集','运动体验','音乐演出']},
 highlights:[{title:'水上娱乐 · 跳东湖',icon:'🌊',tone:'water',copy:'在楚城码头感受武汉夏日的标志性水上体验。',time:'15:45—18:00',place:'楚城码头',notice:'需提前报名',lat:30.5468,lon:114.4125},{title:'岸上运动体验',icon:'🛹',tone:'sport',copy:'足球、尊巴、陆冲、滑板和平衡板体验与教学。',time:'15:00—18:00',place:'楚市草坪',notice:'现场分批体验',lat:30.5458,lon:114.4118},{title:'湖畔主题市集',icon:'☕',tone:'market',copy:'生活潮流、咖啡烘焙、餐饮与潮饮摊位集中开街。',time:'15:00—21:30',place:'楚城前草坪',notice:'65个摊位',lat:30.5462,lon:114.4121},{title:'DJ与乐队演出',icon:'🎵',tone:'music',copy:'晚风、湖景和现场音乐共同组成夜间主场。',time:'18:00—22:00',place:'滑道广场',notice:'建议提前到场',lat:30.5437,lon:114.4096}],
 pois:{scenic:[{name:'楚天台',type:'景点',icon:'🏯',distance:'步行约18分钟',status:'开放',desc:'东湖磨山楚文化核心景点，可俯瞰湖山景色。',lat:30.5451,lon:114.4149,tags:['楚文化','登高观景']},{name:'东湖之眼',type:'景点',icon:'🎡',distance:'步行约12分钟',status:'开放',desc:'磨山景区内湖畔摩天轮，适合傍晚观景拍照。',lat:30.5483,lon:114.4105,tags:['拍照','亲子']},{name:'磨山索道',type:'景点',icon:'🚡',distance:'步行约15分钟',status:'营业中',desc:'串联山顶与湖岸的观景体验，视野开阔。',lat:30.5467,lon:114.4122,tags:['观景','体验']}],toilet:[{name:'楚城入口卫生间',type:'厕所',icon:'🚻',distance:'距你180米',status:'开放',desc:'位于楚城入口东侧，设无障碍厕位。',lat:30.5472,lon:114.4131,tags:['无障碍厕位','人流正常']},{name:'楚市广场卫生间',type:'厕所',icon:'🚻',distance:'距你360米',status:'开放',desc:'位于餐饮市集附近，设母婴台。',lat:30.5458,lon:114.4118,tags:['母婴台','人流正常']},{name:'滑道广场卫生间',type:'厕所',icon:'🚻',distance:'距你620米',status:'较繁忙',desc:'靠近音乐舞台区，演出前可能排队。',lat:30.5437,lon:114.4096,tags:['开放','预计排队6分钟']}],facility:[{name:'码头入口医疗站',type:'医疗',icon:'✚',distance:'距你220米',status:'值守中',desc:'活动固定医疗站，配备医生、急救人员和移动AED。',lat:30.5468,lon:114.4125,tags:['医疗','AED']},{name:'楚市便民服务点',type:'便民',icon:'ⓘ',distance:'距你310米',status:'开放',desc:'提供咨询、失物招领、充电与特殊人群服务。',lat:30.5459,lon:114.4114,tags:['失物招领','充电']},{name:'磨山北门服务点',type:'便民',icon:'♿',distance:'距你850米',status:'开放',desc:'提供无障碍协助、轮椅咨询及交通问询。',lat:30.5511,lon:114.4098,tags:['无障碍','交通']}],merchant:[{name:'东湖精酿实验室',type:'商户',icon:'🍺',distance:'距你260米',status:'营业中',desc:'活动限定精酿与无酒精特调，位于潮饮市集。',lat:30.5461,lon:114.4119,tags:['人均¥48','排队5分钟']},{name:'湖畔咖啡局',type:'商户',icon:'☕',distance:'距你330米',status:'营业中',desc:'咖啡烘焙市集人气摊位，提供低糖饮品。',lat:30.5475,lon:114.4135,tags:['人均¥32','排队3分钟']},{name:'楚风手作',type:'商户',icon:'🎁',distance:'距你410米',status:'营业中',desc:'东湖限定文创、手作徽章及环保袋。',lat:30.5454,lon:114.4108,tags:['文创','无需排队']} ]},
 parking:[{name:'磨山景区P2停车场',distance:'距入口900米',spaces:32,total:260,crowd:'紧张',fee:'¥5/小时',walk:'步行12分钟',lat:30.5521,lon:114.4082},{name:'梅园东停车场',distance:'距入口1.4公里',spaces:186,total:420,crowd:'充裕',fee:'¥4/小时',walk:'步行18分钟',lat:30.5562,lon:114.4171},{name:'楚风园停车场',distance:'接驳约15分钟',spaces:74,total:310,crowd:'一般',fee:'¥6/小时',walk:'游船/接驳可达',lat:30.5704,lon:114.3805}],
 crowds:[{name:'楚城码头',level:'一般',people:'12 / 20人',trend:'上升',wait:'预计等待5分钟',comfort:72,advice:'现在可前往，15:35后预计排队增加'},{name:'生活潮流市集',level:'舒适',people:'约320人',trend:'平稳',wait:'无需排队',comfort:88,advice:'适合现在游玩'},{name:'滑道广场舞台',level:'拥挤',people:'约1,860人',trend:'上升',wait:'前排区约20分钟',comfort:46,advice:'建议17:35前抵达或先去咖啡市集'}],
 schedule:[['15:00','市集开街','楚城前草坪'],['15:00','岸上运动体验','楚市草坪'],['15:45','水上娱乐 · 跳东湖','楚城码头'],['18:00','DJ音乐、乐队演出','滑道广场']],
 routes:{official:{name:'官方半日精华路线',distance:'3.2km',duration:'4小时20分',crowd:'已避开2处高峰',fit:'首次到访 / 朋友同行',stops:['磨山北门','生活潮流市集','楚城码头','滑道广场舞台']}}
};
let routeState={mode:'official',stops:[...DB.routes.official.stops],preference:'避拥堵',saved:false,chatScroll:0};
const OFFICIAL_ROUTES=[{name:'半日精华路线',desc:'兼顾水上、市集和音乐体验，避开入场主通道高峰。',distance:'3.2km',duration:'4小时20分',fit:'首次到访 / 朋友同行',stops:[['磨山北门','14:50 入场 · 排队约6分钟',30.5511,114.4098],['生活潮流市集','15:10 停留35分钟',30.5462,114.4121],['楚城码头','15:55 需确认报名资格',30.5468,114.4125],['滑道广场舞台','18:00 建议提前20分钟',30.5437,114.4096]]},{name:'亲子轻松路线',desc:'减少步行与爬坡，串联亲子体验、休息区和便民设施。',distance:'2.4km',duration:'3小时30分',fit:'亲子家庭 / 低龄儿童',stops:[['磨山北门','14:40 入园',30.5511,114.4098],['东湖之眼','15:00 亲子观景',30.5483,114.4105],['楚市草坪','16:00 运动体验',30.5458,114.4118],['湖畔市集','17:10 用餐休息',30.5462,114.4121]]},{name:'音乐市集路线',desc:'以主题市集和夜间演出为主，适合轻松逛吃与观演。',distance:'2.1km',duration:'4小时',fit:'年轻游客 / 音乐爱好者',stops:[['楚城入口','15:30 集合入场',30.5472,114.4131],['咖啡烘焙市集','15:50 自由逛吃',30.5475,114.4135],['潮流生活市集','17:00 文创体验',30.5462,114.4121],['滑道广场舞台','18:00 音乐演出',30.5437,114.4096]]},{name:'运动挑战路线',desc:'集中体验陆冲、滑板和水上项目，运动强度较高。',distance:'3.8km',duration:'5小时',fit:'运动爱好者 / 朋友组队',stops:[['磨山北门','13:50 提前入园',30.5511,114.4098],['楚市草坪','15:00 岸上运动',30.5458,114.4118],['楚城码头','16:10 水上挑战',30.5468,114.4125],['湖岸休息点','17:30 补水休息',30.5451,114.4108],['滑道广场舞台','18:20 放松观演',30.5437,114.4096]]},{name:'湖景文化路线',desc:'串联磨山文化景点、湖景观景点与活动核心区域。',distance:'4.6km',duration:'5小时30分',fit:'摄影游客 / 文化爱好者',stops:[['磨山北门','13:30 入园',30.5511,114.4098],['楚天台','14:10 登高观景',30.5451,114.4149],['磨山索道','15:10 湖山体验',30.5467,114.4122],['楚城码头','16:20 水岸拍照',30.5468,114.4125],['滑道广场舞台','18:00 夜间演出',30.5437,114.4096]]}];routeState.routeIndex=0;
const SCHEDULE_DAYS=[{date:'9月4日',label:'周五',items:[{time:'15:00',name:'市集开街',place:'楚城前草坪',icon:'☕',lat:30.5462,lon:114.4121,desc:'生活潮流、咖啡烘焙、餐饮与潮饮摊位集中开街，适合先逛市集再前往水上活动。'},{time:'15:00',name:'岸上运动体验',place:'楚市草坪',icon:'🛹',lat:30.5458,lon:114.4118,desc:'足球、尊巴、陆冲、滑板和平衡板体验与教学，现场可按项目排队参与。'},{time:'15:45',name:'水上娱乐 · 跳东湖',place:'楚城码头',icon:'🌊',lat:30.5468,lon:114.4125,desc:'活动标志性水上体验，参与者需提前报名并遵守装备、安全及现场调度要求。'},{time:'18:00',name:'DJ音乐、乐队演出',place:'滑道广场',icon:'🎵',lat:30.5437,lon:114.4096,desc:'湖畔夜间主场，由DJ和乐队接力演出，建议提前到场选择观看区域。'}]},{date:'9月5日',label:'周六',items:[{time:'14:30',name:'亲子水上课堂',place:'楚城码头',icon:'🛟',lat:30.5468,lon:114.4125,desc:'面向亲子家庭的水上安全与体验课堂，需监护人陪同并现场确认资格。'},{time:'16:00',name:'东湖陆冲挑战赛',place:'楚市草坪',icon:'🛹',lat:30.5458,lon:114.4118,desc:'面向不同水平游客的陆地冲浪板挑战与教学体验。'},{time:'17:30',name:'湖畔落日市集',place:'楚城前草坪',icon:'🌇',lat:30.5462,lon:114.4121,desc:'限定文创、咖啡和轻食摊位组成的落日主题市集。'},{time:'19:00',name:'夏夜乐队专场',place:'滑道广场',icon:'🎸',lat:30.5437,lon:114.4096,desc:'多支本地乐队轮番登台，演出持续至夜间。'}]},{date:'9月6日',label:'周日',items:[{time:'15:00',name:'城市运动公开课',place:'楚市草坪',icon:'⚽',lat:30.5458,lon:114.4118,desc:'足球、平衡训练与尊巴等城市运动公开体验。'},{time:'16:00',name:'跳东湖趣味挑战',place:'楚城码头',icon:'🌊',lat:30.5468,lon:114.4125,desc:'活动收官日水上趣味挑战，参与资格与场次以现场安排为准。'},{time:'17:30',name:'市集限定派送',place:'楚城前草坪',icon:'🎁',lat:30.5462,lon:114.4121,desc:'收官日限定徽章和活动周边派送，数量有限。'},{time:'19:30',name:'夏日派对收官演出',place:'滑道广场',icon:'✨',lat:30.5437,lon:114.4096,desc:'三日活动收官演出，包含乐队、DJ与全场互动环节。'}]}];
const POI_CATALOG=[{name:'楚城入口卫生间',type:'厕所',icon:'🚻',distance:'距你180米',status:'开放',desc:'位于楚城入口东侧，设无障碍厕位，当前人流正常。',lat:30.5472,lon:114.4131,tags:['无障碍','开放中']},{name:'楚市直饮水补给点',type:'补水点',icon:'💧',distance:'距你210米',status:'可使用',desc:'提供直饮水和常温饮水补给，请自带水杯。',lat:30.5464,lon:114.4124,tags:['免费饮水','自带水杯']},{name:'磨山北门售票处',type:'售票处',icon:'🎫',distance:'距你780米',status:'营业中',desc:'提供景区票务咨询、现场购票及核销协助。',lat:30.5510,lon:114.4099,tags:['票务咨询','现场核销']},{name:'楚天台',type:'主景点',icon:'🏯',distance:'步行约18分钟',status:'开放',desc:'磨山楚文化核心景点，可登高俯瞰东湖湖山景色。',lat:30.5451,lon:114.4149,tags:['楚文化','登高观景']},{name:'磨山游客中心',type:'游客中心',icon:'ⓘ',distance:'距你820米',status:'开放',desc:'提供游览咨询、失物招领、投诉建议及无障碍协助。',lat:30.5512,lon:114.4101,tags:['咨询服务','失物招领']},{name:'楚城码头',type:'码头',icon:'⚓',distance:'距你260米',status:'正常运营',desc:'跳东湖水上活动核心点位，也是湖上游览的重要上下客点。',lat:30.5468,lon:114.4125,tags:['水上活动','上下客点']},{name:'磨山游船站',type:'游船',icon:'⛴',distance:'距你420米',status:'运营中',desc:'提供磨山周边湖上游览服务，班次以现场公告为准。',lat:30.5480,lon:114.4112,tags:['湖上游览','现场购票']},{name:'磨山电瓶车站',type:'电瓶车',icon:'🛺',distance:'距你350米',status:'运营中',desc:'连接磨山北门、楚城与主要景点，客流高峰可能排队。',lat:30.5484,lon:114.4120,tags:['景区接驳','便捷出行']},{name:'楚市便民服务点',type:'便民服务',icon:'🧰',distance:'距你310米',status:'开放',desc:'提供咨询、失物招领、简易药品和特殊人群协助。',lat:30.5459,lon:114.4114,tags:['便民物品','特殊协助']},{name:'湖岸遮阴休息点',type:'休息点',icon:'🪑',distance:'距你290米',status:'可使用',desc:'设遮阴座椅，可短时休息和观湖，高峰期座位有限。',lat:30.5451,lon:114.4108,tags:['遮阴座椅','湖景']},{name:'楚城共享充电点',type:'充电点',icon:'🔋',distance:'距你240米',status:'可借',desc:'设共享充电宝机柜及少量手机应急充电接口。',lat:30.5465,lon:114.4128,tags:['共享充电宝','应急充电']}];
const INTENTS=[['ticket',/门票|购票|买票|退票/],['insurance',/保险|保单|投保/],['parking',/停车|停车场|车位/],['crowd',/人流|客流|拥挤|哪里人少|舒适度/],['location',/我的位置|当前定位|定位|我在哪/],['route',/路线|怎么走|怎么玩|规划/],['highlight',/亮点|特色|有什么好玩/],['facility',/POI|点位|厕所|卫生间|补水|饮水|售票处|游客中心|码头|游船|电瓶车|便民服务|休息点|充电点/],['activity',/活动信息|活动介绍|活动在哪|什么时候|几点|主办/],['merchant',/商户|商家|咖啡|吃饭|精酿|文创/],['facility',/设施|便民|医疗|充电|失物/],['scenic',/景点|周边玩/],['schedule',/日程|演出时间|安排/],['weather',/天气|下雨|高温/],['safety',/安全|求助|受伤|溺水|AED/],['return',/返程|末班|回家/]];
POI_CATALOG.push({name:'码头入口医疗站',type:'医疗点',icon:'✚',distance:'距你220米',status:'值守中',desc:'活动固定医疗站，配备医护人员、急救用品和移动AED。',lat:30.5468,lon:114.4125,tags:['医疗救助','AED']});
DB.pois.facility=POI_CATALOG;
DB.pois.merchant=[{name:'东湖精酿实验室',category:'啤酒饮品',type:'商户',icon:'🍺',distance:'260米',status:'营业中',desc:'活动限定精酿与无酒精特调，位于潮饮市集。',lat:30.5461,lon:114.4119,tags:['人均¥48','排队5分钟']},{name:'湖畔咖啡局',category:'啤酒饮品',type:'商户',icon:'☕',distance:'330米',status:'营业中',desc:'咖啡烘焙市集人气摊位，提供低糖饮品。',lat:30.5475,lon:114.4135,tags:['人均¥32','排队3分钟']},{name:'夏日果饮社',category:'啤酒饮品',type:'商户',icon:'🍹',distance:'380米',status:'营业中',desc:'鲜果气泡饮、冰茶和儿童无糖饮品。',lat:30.5469,lon:114.4113,tags:['人均¥26','排队4分钟']},{name:'楚市烧烤铺',category:'美食',type:'商户',icon:'🍢',distance:'290米',status:'营业中',desc:'提供武汉风味烧烤与活动限定小食。',lat:30.5460,lon:114.4115,tags:['人均¥45','排队8分钟']},{name:'热干面补给站',category:'美食',type:'商户',icon:'🍜',distance:'350米',status:'营业中',desc:'武汉热干面、豆皮与清淡儿童餐。',lat:30.5457,lon:114.4111,tags:['人均¥24','排队6分钟']},{name:'湖畔轻食所',category:'美食',type:'商户',icon:'🥪',distance:'420米',status:'营业中',desc:'三明治、沙拉和便携能量餐。',lat:30.5454,lon:114.4109,tags:['人均¥38','无需排队']},{name:'楚风手作',category:'纪念品',type:'商户',icon:'🎁',distance:'410米',status:'营业中',desc:'东湖限定文创、手作徽章及环保袋。',lat:30.5454,lon:114.4108,tags:['文创','无需排队']},{name:'跳东湖限定商店',category:'纪念品',type:'商户',icon:'👕',distance:'450米',status:'营业中',desc:'活动限定T恤、毛巾和主题周边。',lat:30.5452,lon:114.4106,tags:['限定周边','排队3分钟']}];
const LOCATION_SCENICS=[...DB.pois.scenic,{name:'楚城码头',type:'景点',icon:'⚓',distance:'步行约5分钟',status:'开放',desc:'跳东湖水上活动核心点位与湖岸观景区。',lat:30.5468,lon:114.4125,tags:['湖景','水上活动']},{name:'磨山樱园',type:'景点',icon:'🌸',distance:'步行约20分钟',status:'开放',desc:'磨山代表性园林景点，适合散步与拍照。',lat:30.5526,lon:114.4148,tags:['园林','拍照']},{name:'滑道广场',type:'景点',icon:'🎵',distance:'步行约13分钟',status:'开放',desc:'活动音乐演出主舞台与夜间聚集区。',lat:30.5437,lon:114.4096,tags:['音乐舞台','夜游']}];
const LOCATION_FOODS=[...DB.pois.merchant.filter(x=>x.category==='美食'),...DB.pois.merchant.filter(x=>x.category==='啤酒饮品')].slice(0,6);
const LOCATION_ACTIVITIES=SCHEDULE_DAYS.flatMap(day=>day.items.map(item=>({...item,date:day.date,status:'可参与',distance:item.place==='楚城码头'?'约260米':'约320米'}))).slice(0,6);
function showScreen(name){home.classList.toggle('active',name==='home');chat.classList.toggle('active',name==='chat');routeScreen.classList.toggle('active',name==='route')}
function detectIntent(q){return (INTENTS.find(([,re])=>re.test(q))||['fallback'])[0]}
function startVoice(){voicePanel.classList.add('open');transcript.textContent='请说出你的问题';$('#voiceTitle').textContent='正在聆听…';const lines=['我想问一下…','我想问一下附近…','我想问一下附近停车场还有没有位置'];let i=0;clearInterval(startVoice.timer);startVoice.timer=setInterval(()=>{transcript.textContent=lines[i++];if(i===lines.length){clearInterval(startVoice.timer);setTimeout(()=>finishVoice(lines.at(-1)),650)}},650)}
function finishVoice(text){$('#voiceTitle').textContent='识别完成';transcript.textContent=text;setTimeout(()=>{voicePanel.classList.remove('open');showScreen('chat');ask(text)},500)}
const holdVoice={active:false,cancel:false,startY:0,text:'',timer:null};
function startHoldVoice(e){e.preventDefault();holdVoice.active=true;holdVoice.cancel=false;holdVoice.startY=e.clientY;holdVoice.text='';e.currentTarget.querySelector('b').textContent='上滑取消';e.currentTarget.setPointerCapture?.(e.pointerId);voicePanel.classList.add('open');voicePanel.classList.remove('cancel-mode');voicePanel.setAttribute('aria-hidden','false');$('#voiceTitle').textContent='正在聆听…';$('#voiceHint').textContent='松开发送';transcript.textContent='请开始说话';const lines=['我想了解…','我想了解一下本次活动…','我想了解一下本次活动的亮点和推荐路线'];let i=0;clearInterval(holdVoice.timer);holdVoice.timer=setInterval(()=>{if(!holdVoice.active)return;holdVoice.text=lines[Math.min(i++,lines.length-1)];transcript.textContent=holdVoice.text},520)}
function moveHoldVoice(e){if(!holdVoice.active)return;holdVoice.cancel=e.clientY<holdVoice.startY-65;voicePanel.classList.toggle('cancel-mode',holdVoice.cancel);e.currentTarget.querySelector('b').textContent=holdVoice.cancel?'松开取消':'上滑取消';$('#voiceTitle').textContent=holdVoice.cancel?'松开取消':'正在聆听…';$('#voiceHint').textContent=holdVoice.cancel?'已上滑，松开取消':'松开发送'}
function endHoldVoice(e){if(!holdVoice.active)return;e.preventDefault();holdVoice.active=false;clearInterval(holdVoice.timer);e.currentTarget.querySelector('b').textContent='按住说话';e.currentTarget.releasePointerCapture?.(e.pointerId);if(holdVoice.cancel){voicePanel.classList.remove('open','cancel-mode');voicePanel.setAttribute('aria-hidden','true');toast('已取消语音输入');return}finishVoice(holdVoice.text||'请介绍一下本次活动')}
function cancelHoldVoice(e){if(!holdVoice.active)return;holdVoice.cancel=true;endHoldVoice(e)}
function initChat(){messages.innerHTML=`<div class="msg welcome-message"><div class="msg-avatar">跳</div><div class="bubble">你好，我是东湖小跳。可以问我活动亮点、推荐路线、停车余位、景点人流、购票保险和周边设施。<p class="welcome-guide">先为你送上本次活动的基本信息：</p></div></div>`;activityCard(messages.querySelector('.welcome-message .bubble'))}
function ask(q){if(!q.trim())return;addUser(q);input.value='';const loading=document.createElement('div');loading.className='msg';loading.innerHTML='<div class="msg-avatar">跳</div><div class="bubble"><span class="typing"><i></i><i></i><i></i></span></div>';messages.append(loading);scrollEnd();setTimeout(()=>{loading.remove();respond(detectIntent(q))},420)}
function respond(intent){const map={activity:['以下是本次活动的官方基础信息。具体节目可能根据天气和现场调度调整。',activityCard],highlight:['本次跳东湖由水上体验、运动、市集与音乐四个板块组成，以下是最值得关注的亮点：',highlightCards],location:['已为你定位到东湖磨山景区活动区域，当前位置靠近楚城入口。以下是定位信息和步行可达的推荐：',locationCard],route:['我推荐一条兼顾活动亮点与现场客流的半日路线。点击卡片可查看官方路线，也可自定义或让Agent重排。',routeCard],toilet:['已按当前位置找到附近卫生间，按距离与开放状态排序：',t=>poiCards(DB.pois.toilet,t)],facility:['以下是附近可用的便民及医疗设施。动态状态为演示数据：',t=>poiCards(DB.pois.facility,t)],merchant:['以下商户正在营业，可查看详情或直接导航到摊位：',t=>poiCards(DB.pois.merchant,t)],scenic:['磨山景区内这些景点步行可达，可查看详情和导航：',t=>poiCards(DB.pois.scenic,t)],ticket:['活动采用实名制购票及核销码入场。请通过官方渠道购买，并仔细核对观演人信息。',t=>purchaseCard('ticket',t)],insurance:['参与跳水需按活动要求购买保险。以下入口为演示配置，最终产品及条款以合作保险平台为准。',t=>purchaseCard('insurance',t)],parking:['以下停车余位、拥挤程度为演示数据。建议优先选择余位充足且接驳方便的停车场：',parkingCards],crowd:['以下为各点位模拟人流状态与游玩舒适度，现场请以官方广播和管控为准：',crowdCards],schedule:['这是活动首日主要日程，可订阅节目提醒：',scheduleCard],weather:['当前东湖磨山景区多云、31°C，体感约33°C。紫外线较强，适合轻薄透气穿着，并注意防晒和及时补水。',weatherCard],safety:['现场设置4个固定医疗站、1辆救护车和专业水上救生力量。紧急情况请立即联系现场人员。',safetyCard],return:['游船和景区电瓶车计划延时服务至22:30，建议21:50后根据实时队列选择返程方式。',returnCard],fallback:['我可以提供活动、亮点、路线、POI、票务、保险、停车、人流、天气、安全和返程服务。',null]};const [text,card]=map[intent]||map.fallback;streamAnswer(text,card)}
function streamAnswer(text,after){const wrap=document.createElement('div');wrap.className='msg';wrap.innerHTML='<div class="msg-avatar">跳</div><div class="bubble"><span class="stream-cursor"></span></div>';messages.append(wrap);const target=wrap.querySelector('.bubble');let i=0;const timer=setInterval(()=>{target.firstChild.textContent=text.slice(0,i+=2);scrollEnd();if(i>=text.length){clearInterval(timer);target.firstChild.classList.remove('stream-cursor');after?.(target);appendStatus(target);speakAgent(text);scrollEnd()}},18)}
function appendStatus(t){if(!t)return;t.insertAdjacentHTML('beforeend',`<div class="card-status"><span>数据更新于 ${CONFIG.updatedAt}</span></div>`)}
function activityCard(t){const a=DB.activity;t.insertAdjacentHTML('beforeend',`<article class="info-card activity-info-card" data-activity-detail><div class="info-brand"><span>跳</span><div><small>OFFICIAL EVENT</small><b>${a.title}</b></div></div><dl><div><dt>日期</dt><dd>${a.date}</dd></div><div><dt>时间</dt><dd>${a.time}</dd></div><div><dt>地点</dt><dd class="activity-place"><span>${a.place}</span><button data-card-action="activity-nav">导航</button></dd></div><div><dt>主办</dt><dd>${a.hosts}</dd></div></dl><div class="tag-row">${a.features.map(x=>`<span>${x}</span>`).join('')}</div><div class="activity-actions"><button data-card-action="activity-detail">活动介绍</button><button class="primary" data-card-action="schedule">活动日程</button></div></article>`)}
function highlightCards(t){const el=document.createElement('div');el.className='highlight-list';el.innerHTML=DB.highlights.map((x,i)=>`<button class="highlight-list-card ${x.tone}" data-highlight="${i}"><span class="highlight-list-icon">${x.icon}</span><span class="highlight-list-content"><small>${x.time} · ${x.place}</small><b>${x.title}</b><p>${x.copy}</p><em>${x.notice}</em></span><i>详情 ›</i></button>`).join('');t.append(el)}
function routeCard(t){t.insertAdjacentHTML('beforeend',`<article class="route-library-card"><div class="route-library-head"><span>官方推荐</span><b>5条精选游玩路线</b><small>根据同行人群和体验偏好选择</small></div><div class="route-preview-list">${OFFICIAL_ROUTES.map((r,i)=>`<button data-official-open="${i}"><em>路线${i+1}</em><span><b>${r.name}</b><small>${r.distance} · ${r.duration} · ${r.fit}</small></span><i>›</i></button>`).join('')}</div><button class="route-more" data-official-open="0">查看更多路线</button></article>`)}
function poiCards(list,t){if(list===DB.pois.merchant){merchantCards(t);return}const el=document.createElement('div');el.className='place-list';el.innerHTML=list.map(p=>`<button class="place-card" data-place="${pack(p)}"><span class="place-thumb type-${p.type}">${p.icon}</span><span><b>${p.name}</b><small>${p.distance} · ${p.status}</small><em>${p.tags.join(' · ')}</em></span><i>›</i></button>`).join('');t.append(el)}
function poiCatalogCard(t){poiCards(POI_CATALOG,t)}
function merchantGridHTML(category='全部'){const list=category==='全部'?DB.pois.merchant:DB.pois.merchant.filter(x=>x.category===category);return list.map(p=>`<button class="merchant-tile" data-place="${pack(p)}"><span class="merchant-art">${p.icon}</span><em>${p.category}</em><b>${p.name}</b><small>${p.distance} · ${p.status}</small><i>${p.tags.join(' · ')}</i></button>`).join('')}
function merchantCards(t){const cats=['全部','啤酒饮品','美食','纪念品'],el=document.createElement('div');el.className='merchant-browser';el.innerHTML=`<nav class="merchant-tabs">${cats.map((x,i)=>`<button class="${i?'':'active'}" data-merchant-category="${x}">${x}</button>`).join('')}</nav><div class="merchant-grid">${merchantGridHTML()}</div>`;el.onclick=e=>{const tab=e.target.closest('[data-merchant-category]');if(!tab)return;e.stopPropagation();el.querySelectorAll('[data-merchant-category]').forEach(x=>x.classList.toggle('active',x===tab));el.querySelector('.merchant-grid').innerHTML=merchantGridHTML(tab.dataset.merchantCategory)};t.append(el)}
function purchaseCard(type,t){const ticket=type==='ticket',url=ticket?CONFIG.ticketUrl:CONFIG.insuranceUrl;t.insertAdjacentHTML('beforeend',`<article class="purchase-card ${type}"><div class="purchase-icon">${ticket?'🎫':'🛡'}</div><div class="purchase-title"><small>${ticket?'活动官方票务':'参与者保险'}</small><b>${ticket?'2026跳东湖夏日派对门票':'水上活动意外保障'}</b></div><div class="purchase-price"><span>${ticket?'价格以官方平台为准':'保费以承保页面为准'}</span><strong>待正式发布</strong></div><ul>${ticket?'<li>实名制购买及核销码入场</li><li>仅支持整单整退</li>':'<li>需覆盖活动参与日期</li><li>被保险人信息须与报名一致</li>'}</ul><button class="card-primary" data-external="${url}" data-external-type="${ticket?'票务':'保险'}">${ticket?'前往官方购票':'前往保险平台'} ↗</button><p class="third-note">演示入口 · 待替换正式商品地址 · 最终规则以第三方平台为准</p></article>`)}
function parkingCards(t){const el=document.createElement('div');el.className='parking-list';el.innerHTML=`<div class="parking-toolbar"><b>附近停车场</b><button data-card-action="sort-parking">按余位排序</button></div>`+DB.parking.map((p,i)=>parkingHTML(p,i)).join('');t.append(el)}
function parkingHTML(p,i){const ratio=Math.round(p.spaces/p.total*100),level=p.crowd==='紧张'?'danger':p.crowd==='一般'?'warn':'ok';return `<article class="parking-card" data-parking-index="${i}"><div class="parking-top"><span class="parking-p">P</span><div><b>${p.name}</b><small>${p.distance} · ${p.walk}</small></div><em class="${level}">${p.crowd}</em></div><div class="parking-space"><strong>${p.spaces}</strong><span>剩余车位 / 共${p.total}位</span><i><u style="width:${ratio}%"></u></i></div><div class="parking-foot"><span>${p.fee}</span><button data-drive="${pack(p)}">驾车导航</button></div></article>`}
function crowdCards(t){const el=document.createElement('div');el.className='crowd-list';el.innerHTML=DB.crowds.map(p=>`<article class="crowd-card"><div class="crowd-title"><div><b>${p.name}</b><small>${p.people} · ${p.wait}</small></div><em class="level-${p.level}">${p.level}</em></div><div class="comfort"><span>游玩舒适度 <b>${p.comfort}</b></span><i><u style="width:${p.comfort}%"></u></i></div><div class="crowd-advice"><span>${p.trend==='上升'?'↗':'→'} ${p.trend}</span>${p.advice}</div></article>`).join('');t.append(el)}
function scheduleItems(day){return day.items.map(x=>{const item={...x,date:day.date},data=pack(item),started=day.date==='9月4日'&&x.time<='15:08';return `<div class="schedule-row" data-schedule-detail="${data}"><time>${x.time}</time><span class="schedule-title"><b>${x.name}</b><small>${x.place} · 点击查看详情</small></span><div class="schedule-actions">${started?'<em class="live-status">进行中</em>':`<button data-subscribe-name="${esc(x.name)}" onclick="showWechatSubscribe('${data}');event.stopImmediatePropagation()">订阅</button>`}<button class="primary" data-schedule-nav="${data}">导航</button></div></div>`}).join('')}
function scheduleCard(t){const first=SCHEDULE_DAYS[0];t.insertAdjacentHTML('beforeend',`<article class="schedule-card schedule-three-day"><div class="schedule-tabs">${SCHEDULE_DAYS.map((d,i)=>`<button class="${i?'':'active'}" data-schedule-day="${i}"><b>${d.date}</b><small>${d.label}</small></button>`).join('')}</div><div class="schedule-day-list">${scheduleItems(first)}</div><p class="schedule-tip">点击活动可查看介绍与现场导航</p></article>`)}
function renderActivityProcess(){const body=$('#activityProcessBody');if(!body)return;body.innerHTML='';scheduleCard(body)}
function toggleActivityProcess(force){const panel=$('#activityProcessPanel'),entry=$('#processEntry'),open=typeof force==='boolean'?force:!panel.classList.contains('open');panel.classList.toggle('open',open);panel.setAttribute('aria-hidden',String(!open));entry.classList.toggle('active',open);entry.querySelector('i').textContent=open?'⌃':'⌄'}
let waterAmount=400,waterCount=2;
function toggleSideMenu(force){const menu=$('#sideMenu'),overlay=$('#menuOverlay'),open=typeof force==='boolean'?force:!menu.classList.contains('open');menu.classList.toggle('open',open);overlay.classList.toggle('open',open);menu.setAttribute('aria-hidden',String(!open))}
function openWaterApp(){toggleSideMenu(false);[home,chat,routeScreen].forEach(x=>x.classList.remove('active'));$('#waterApp').classList.add('active')}
function closeWaterApp(){$('#waterApp').classList.remove('active');chat.classList.add('active')}
function toggleWaterReminder(){showWechatSubscribe(pack({name:'喝水提醒',date:'今天',time:'每60分钟',place:'东湖磨山景区'}))}
function checkInWater(){const before=waterAmount;waterAmount=Math.min(10000,waterAmount+200);if(waterAmount===before){toast('今日饮水记录已达到10000ml上限');return}waterCount++;$('#waterAmount').textContent=waterAmount;const fill=Math.min(100,waterAmount/20);$('#waterProgress').style.width=`${fill}%`;$('#cupWater').style.height=`${fill}%`;$('#cupWater').dataset.amount=`${waterAmount}ml`;$('#waterStatus').textContent=`今天已打卡 ${waterCount} 次`;const badge=$('#waterGoalBadge');badge.classList.toggle('show',waterAmount>=2000);if(before<2000&&waterAmount>=2000)badge.classList.add('celebrate');$('#waterRecords').insertAdjacentHTML('afterbegin',`<li><time>${waterDateTime()}</time><span>喝水打卡</span><b>200ml</b></li>`);updateWaterRecordList();toast(waterAmount>=2000?`今日已达标 · 累计${waterAmount}ml`:'喝水打卡成功 +200ml')}
function locationRecommendationHTML(type='activity'){if(type==='activity')return LOCATION_ACTIVITIES.map(x=>`<button class="location-recommend-card activity-recommend" data-schedule-info="${pack(x)}"><span>${x.icon}</span><em>${x.date} · ${x.time}</em><b>${x.name}</b><small>${x.place} · ${x.distance}</small><i>查看活动</i></button>`).join('');if(type==='scenic')return LOCATION_SCENICS.map(x=>`<button class="location-recommend-card scenic-recommend" data-place="${pack(x)}"><span>${x.icon}</span><em>${x.status}</em><b>${x.name}</b><small>${x.distance} · ${(x.tags||[])[0]}</small><i>查看景点</i></button>`).join('');return LOCATION_FOODS.map(x=>`<button class="location-recommend-card food-recommend" data-place="${pack(x)}"><span>${x.icon}</span><em>${x.status}</em><b>${x.name}</b><small>${x.distance} · ${x.tags[0]}</small><i>查看商户</i></button>`).join('')}
function switchLocationTab(button,type){const card=button.closest('.location-card');card.querySelectorAll('[data-location-tab]').forEach(x=>x.classList.toggle('active',x===button));card.querySelector('.nearby-recommend').innerHTML=locationRecommendationHTML(type)}
function locationCard(t){t.insertAdjacentHTML('beforeend',`<article class="location-card"><div class="location-map"><i class="location-pulse"></i><span>你</span><em>楚城入口附近</em><small>定位精度约 12 米</small></div><div class="location-summary"><span>当前位置</span><b>东湖磨山景区 · 楚城入口</b><small>距活动主会场约 320 米 · 步行约 5 分钟</small></div><nav class="location-recommend-tabs"><button class="active" data-location-tab="activity" onclick="switchLocationTab(this,'activity');event.stopPropagation()">活动推荐</button><button data-location-tab="scenic" onclick="switchLocationTab(this,'scenic');event.stopPropagation()">景点推荐</button><button data-location-tab="food" onclick="switchLocationTab(this,'food');event.stopPropagation()">美食推荐</button></nav><div class="nearby-recommend">${locationRecommendationHTML('activity')}</div></article>`)}
function weatherCard(t){t.insertAdjacentHTML('beforeend',`<article class="weather-card weather-detail-card"><div class="weather-now"><span>⛅</span><div><strong>31°</strong><b>多云</b><small>体感33° · 东南风2级</small></div><em>紫外线较强</em></div><div class="weather-metrics"><span><b>58%</b><small>湿度</small></span><span><b>20%</b><small>降雨概率</small></span><span><b>18:52</b><small>日落</small></span></div><h4>今日游玩建议</h4><div class="weather-advice"><span>👕<b>穿衣</b><small>轻薄透气，备一件防晒衣</small></span><span>🧴<b>防晒</b><small>每2小时补涂防晒霜</small></span><span>💧<b>喝水</b><small>少量多次，每小时补水</small></span><span>🌦<b>天气</b><small>留意临时雷雨提醒</small></span></div></article>`)}
function safetyCard(t){const station={name:'码头入口医疗站',type:'医疗点',icon:'✚',distance:'距你220米 · 步行约3分钟',status:'值守中',desc:'活动固定医疗站，配备医护人员、急救用品和移动AED。',lat:30.5468,lon:114.4125,tags:['医护值守','AED','急救用品']};t.insertAdjacentHTML('beforeend',`<article class="safety-card medical-map-card"><div class="medical-map"><span class="medical-route"></span><i class="you-pin">你</i><i class="medical-pin">✚</i><small>约220米</small></div><div class="medical-info"><span><em>最近医疗点</em><b>${station.name}</b><small>${station.distance} · ${station.status}</small></span><button data-route-stop="${pack(station)}">去导航</button></div><button class="sos-btn" onclick="showEmergencyContacts();event.stopImmediatePropagation()">紧急求助</button></article>`)}
function returnCard(t){const exits=[{name:'磨山北门出口',type:'出口',icon:'🚪',distance:'步行约16分钟',status:'开放至22:30',desc:'靠近电瓶车终点和网约车推荐上客区，适合前往鲁磨路方向。',lat:30.5511,lon:114.4098,tags:['电瓶车接驳','网约车上客点']},{name:'楚城出口',type:'出口',icon:'↗',distance:'步行约8分钟',status:'开放至22:30',desc:'距离活动核心区较近，可步行前往楚城码头游船站或转乘景区接驳。',lat:30.5472,lon:114.4131,tags:['临近码头','步行优先']}];t.insertAdjacentHTML('beforeend',`<article class="return-card return-exit-card"><div class="return-service"><span>⛴ 游船至22:30</span><span>🛺 电瓶车4条线路</span></div><b class="return-title">选择返程出口</b>${exits.map(x=>`<div class="exit-row" data-place="${pack(x)}"><span class="exit-icon">${x.icon}</span><span><b>${x.name}</b><small>${x.distance} · ${x.status}</small></span><button data-route-stop="${pack(x)}">去导航</button></div>`).join('')}<p>点击出口可查看接驳说明与导航信息</p></article>`)}
function addUser(q){messages.insertAdjacentHTML('beforeend',`<div class="msg user"><div class="bubble">${esc(q)}</div></div>`);scrollEnd()}
function showPlace(p){const nav=navUrl(p,'walk');detailSheet.className='sheet open';detailSheet.innerHTML=`<div class="sheet-card"><div class="sheet-handle"></div><div class="sheet-head"><h2>${p.name}</h2><button data-close>×</button></div><div class="place-hero">${p.icon||'📍'}</div><div class="place-meta">${(p.tags||[p.status]).map(x=>`<span>${x}</span>`).join('')}</div><p>${p.desc}</p><p><b>${p.distance}</b><br>导航会尝试调用已安装的高德地图，无法调起时打开网页版。</p><div class="sheet-actions"><button data-close>继续问小跳</button><a class="primary" href="${nav}" target="_blank" rel="noopener">开始导航 ↗</a></div></div>`}
function showHighlight(i){const x=DB.highlights[i];detailSheet.className='sheet open';detailSheet.innerHTML=`<div class="sheet-card"><div class="sheet-handle"></div><div class="sheet-head"><h2>${x.title}</h2><button data-close>×</button></div><div class="highlight-detail-hero ${x.tone}"><span>${x.icon}</span><div><small>${x.time}</small><b>${x.place}</b></div></div><div class="place-meta"><span>${x.time}</span><span>${x.place}</span><span>${x.notice}</span></div><p>${x.copy}</p><p>这是“2026跳东湖夏日派对”的核心体验板块。建议根据活动时间提前到达，水上及运动项目须听从工作人员指引；具体安排可能因天气、安全管控和现场客流临时调整。</p><div class="sheet-actions"><button data-close>继续问小跳</button><a class="primary" href="${navUrl(x,'walk')}" target="_blank" rel="noopener">去导航 ↗</a></div></div>`}
function showActivity(){const a=DB.activity;detailSheet.className='sheet open';detailSheet.innerHTML=`<div class="sheet-card"><div class="sheet-handle"></div><div class="sheet-head"><h2>${a.title}</h2><button data-close>×</button></div><div class="activity-detail-hero"><span>跳</span><div><small>BE WATER · MY FRIEND</small><b>在东湖，把武汉的夏天跳进水里</b></div></div><div class="place-meta"><span>${a.date}</span><span>${a.time}</span></div><p>“跳东湖”是一场融合水上娱乐、城市运动、湖畔市集与现场音乐的夏日派对。游客可以从下午进入磨山景区，在楚城码头体验标志性水上项目，随后逛主题市集、参与岸上运动，并在晚风中观看音乐演出。</p><p><b>活动地点</b><br>${a.place}</p><p>水上项目需遵守报名资格、安全装备及现场调度要求；节目时间可能因天气和客流临时调整，请以现场通知为准。</p><div class="sheet-actions"><button data-close>继续问小跳</button><a class="primary" href="${navUrl({name:a.place,lat:30.5468,lon:114.4125},'walk')}" target="_blank" rel="noopener">去导航 ↗</a></div></div>`}
function showScheduleDetail(item){detailSheet.className='sheet open';detailSheet.innerHTML=`<div class="sheet-card"><div class="sheet-handle"></div><div class="sheet-head"><h2>${item.name}</h2><button data-close>×</button></div><div class="schedule-detail-hero"><span>${item.icon}</span><div><small>${item.date} · ${item.time}</small><b>${item.place}</b></div></div><div class="place-meta"><span>${item.date}</span><span>${item.time}</span><span>${item.place}</span></div><p>${item.desc}</p><p>请提前到达活动区域并听从现场工作人员引导。具体安排可能根据天气、安全管控及客流情况调整。</p><div class="sheet-actions"><button data-close>继续问小跳</button><a class="primary" href="${navUrl(item,'walk')}" target="_blank" rel="noopener">导航到现场 ↗</a></div></div>`}
function confirmExternal(url,type){detailSheet.className='sheet open';detailSheet.innerHTML=`<div class="sheet-card compact-sheet"><div class="sheet-handle"></div><div class="sheet-head"><h2>即将前往第三方平台</h2><button data-close>×</button></div><p>你将离开“东湖小跳”，前往${type}演示入口。当前地址待替换为本活动正式商品页，价格、库存、保障及售后规则以第三方平台为准。</p><div class="sheet-actions"><button data-close>取消</button><a class="primary" href="${url}" target="_blank" rel="noopener">确认前往 ↗</a></div></div>`}
function showEmergencyContacts(){detailSheet.className='sheet open';detailSheet.innerHTML=`<div class="sheet-card emergency-sheet"><div class="sheet-handle"></div><div class="sheet-head"><h2>现场紧急求助</h2><button data-close>×</button></div><div class="emergency-alert"><span>!</span><div><b>如有生命危险，请优先拨打120</b><small>说明当前位置：东湖磨山景区跳东湖活动现场</small></div></div><div class="contact-list"><a href="tel:120"><span>🚑</span><div><b>医疗急救</b><small>国家急救电话</small></div><strong>120</strong></a><a href="tel:027-00000001"><span>✚</span><div><b>活动医疗指挥</b><small>演示号码 · 待替换正式联系人</small></div><strong>拨打</strong></a><a href="tel:027-00000002"><span>🛟</span><div><b>现场安全负责人</b><small>演示号码 · 待替换正式联系人</small></div><strong>拨打</strong></a></div><p>拨号前请确认联系人信息。除120外，页面中的活动联系人号码仅用于交互演示。</p><div class="sheet-actions single"><button data-close>继续问小跳</button></div></div>`}
let pendingSubscribe=null;
function showWechatSubscribe(data){pendingSubscribe=unpack(data);detailSheet.className='sheet open wechat-subscribe-layer';detailSheet.innerHTML=`<div class="wechat-subscribe-dialog"><div class="wechat-app-row"><span>跳</span><b>东湖小跳 申请</b></div><h2>发送一次以下消息通知</h2><div class="wechat-permission-row"><span class="wechat-check">✓</span><div><b>活动开始提醒</b><small>${pendingSubscribe.name} · ${pendingSubscribe.date} ${pendingSubscribe.time}</small><em>将在活动开始前15分钟通知</em></div><i>i</i></div><div class="wechat-dialog-actions"><button data-close>取消</button><button class="allow" onclick="confirmWechatSubscribe();event.stopImmediatePropagation()">允许</button></div><label><input type="checkbox" checked> 总是保持以上选择，不再询问</label><p>本弹窗为微信订阅消息授权交互模拟</p></div>`}
function confirmWechatSubscribe(){if(!pendingSubscribe)return;const name=pendingSubscribe.name;document.querySelectorAll('[data-subscribe-name]').forEach(btn=>{if(btn.dataset.subscribeName===name){btn.textContent='已订阅';btn.disabled=true;btn.classList.add('subscribed')}});if(name==='喝水提醒'){$('#waterReminderBtn').textContent='已订阅';$('#waterReminderBtn').classList.add('subscribed')}detailSheet.className='sheet';toast(name==='喝水提醒'?'喝水提醒订阅成功':`已订阅「${name}」，开始前15分钟提醒`);pendingSubscribe=null}
function openRoute(index=0){routeState.chatScroll=messages.scrollTop;routeState.routeIndex=Number.isFinite(+index)?+index:0;showScreen('route');renderRoute()}
function renderRoute(){const r=OFFICIAL_ROUTES[routeState.routeIndex];$('#routeModeText').textContent=`路线${routeState.routeIndex+1} · ${r.name}`;$('#routeBody').innerHTML=`<nav class="route-line-tabs" aria-label="官方路线切换">${OFFICIAL_ROUTES.map((x,i)=>`<button class="${i===routeState.routeIndex?'active':''}" data-official-select="${i}"><span>路线${i+1}</span><b>${x.name}</b></button>`).join('')}</nav><section class="route-overview"><span>官方推荐 · 路线${routeState.routeIndex+1}</span><h2>${r.name}</h2><p>${r.desc}</p><div class="official-route-metrics"><span><b>${r.distance}</b><small>步行距离</small></span><span><b>${r.duration}</b><small>预计时长</small></span></div><em>适合：${r.fit}</em></section>${routeTimeline(r)}<aside class="route-tip"><b>官方提醒</b>路线和活动开放状态可能因天气、安全管控及现场客流调整。</aside>`;requestAnimationFrame(()=>{const tabs=$('#routeBody').querySelector('.route-line-tabs'),active=tabs?.querySelector('.active');if(tabs&&active)tabs.scrollLeft=Math.max(0,active.offsetLeft-(tabs.clientWidth-active.offsetWidth)/2)})}
function routeTimeline(r){return `<section class="route-timeline">${r.stops.map((x,i)=>`<div><i>${i+1}</i><span><b>${x[0]}</b><small>${x[1]}</small></span><button data-route-stop="${pack({name:x[0],lat:x[2],lon:x[3]})}">去导航</button></div>`).join('')}</section>`}
function stopEditor(x,i){return `<div class="stop-editor" data-stop="${i}"><span>☷</span><i>${i===0?'起':i===routeState.stops.length-1?'终':i}</i><b>${x}</b><button data-remove-stop="${i}">×</button></div>`}
function updateRouteSummary(){const km=(1.1+routeState.stops.length*.52).toFixed(1),mins=routeState.stops.length*55;$('#routeSummary').textContent=`${km}km · ${Math.floor(mins/60)}小时${mins%60}分`}
function saveRoute(){routeState.saved=true;toast('路线已保存');setTimeout(()=>{showScreen('chat');messages.scrollTop=routeState.chatScroll;const wrap=document.createElement('div');wrap.className='msg';wrap.innerHTML=`<div class="msg-avatar">跳</div><div class="bubble">路线已更新并保存。<div class="route-saved"><b>${routeState.mode==='agent'?'Agent专属路线':'我的自定义路线'}</b><span>${routeState.stops.join(' → ')}</span><button data-open-route>查看路线</button></div></div>`;messages.append(wrap);scrollEnd()},400)}
function navUrl(p,mode='walk'){return `${CONFIG.amapBase}?to=${p.lon},${p.lat},${encodeURIComponent(p.name)}&mode=${mode}&coordinate=gaode&callnative=1`}
function pack(v){return encodeURIComponent(JSON.stringify(v))}function unpack(v){return JSON.parse(decodeURIComponent(v))}function scrollEnd(){requestAnimationFrame(()=>messages.scrollTop=messages.scrollHeight)}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function toast(t){const e=$('#toast');e.textContent=t;e.className='show';setTimeout(()=>e.className='',1800)}
function renderScenarioList(keyword=''){const list=window.DEMO_SCENARIOS||[],q=keyword.trim().toLowerCase(),filtered=list.filter(x=>[x.group,x.title,x.prompt,x.card,x.description].join(' ').toLowerCase().includes(q)),groups=filtered.reduce((all,item)=>((all[item.group]??=[]).push(item),all),{}),root=$('#scenarioList');$('#scenarioCount').textContent=filtered.length;root.innerHTML=Object.entries(groups).map(([group,items])=>`<section class="scenario-group"><div class="scenario-group-title">${esc(group)}</div>${items.map(item=>{const index=list.indexOf(item)+1;return `<button class="scenario-item" data-demo-id="${esc(item.id)}"><span class="scenario-index">${String(index).padStart(2,'0')}</span><b>${esc(item.title)}</b><em>${esc(item.card)}</em><p>${esc(item.description)}</p><small>演示问题：${esc(item.prompt)}</small></button>`}).join('')}</section>`).join('')||'<div class="scenario-empty">没有找到匹配的演示场景</div>'}
function runScenario(id){const item=(window.DEMO_SCENARIOS||[]).find(x=>x.id===id);if(!item)return;document.querySelectorAll('[data-demo-id]').forEach(x=>x.classList.toggle('active',x.dataset.demoId===id));detailSheet.className='sheet';voicePanel.classList.remove('open');initChat();showScreen('chat');setTimeout(()=>ask(item.prompt),180)}
$('#voiceOrb').onclick=startVoice;$('#inlineVoice').onclick=startVoice;$('#cancelVoice').onclick=()=>{clearInterval(startVoice.timer);voicePanel.classList.remove('open')};$('#sendBtn').onclick=()=>ask(input.value);input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask(input.value)}};$('#scenarioSearch').oninput=e=>renderScenarioList(e.target.value);$('#scenarioList').onclick=e=>{const item=e.target.closest('[data-demo-id]');if(item)runScenario(item.dataset.demoId)};
document.addEventListener('click',e=>{const open=e.target.closest('[data-official-open]');if(open){e.stopImmediatePropagation();openRoute(+open.dataset.officialOpen);return}const select=e.target.closest('[data-official-select]');if(select){e.stopImmediatePropagation();routeState.routeIndex=+select.dataset.officialSelect;renderRoute();return}const stop=e.target.closest('[data-route-stop]');if(stop){e.stopImmediatePropagation();window.open(navUrl(unpack(stop.dataset.routeStop),'walk'),'_blank')}});
document.addEventListener('click',e=>{const dayTab=e.target.closest('[data-schedule-day]');if(dayTab){e.stopImmediatePropagation();const card=dayTab.closest('.schedule-card'),day=SCHEDULE_DAYS[+dayTab.dataset.scheduleDay];card.querySelectorAll('[data-schedule-day]').forEach(x=>x.classList.toggle('active',x===dayTab));card.querySelector('.schedule-day-list').innerHTML=scheduleItems(day);return}const info=e.target.closest('[data-schedule-info]');if(info){e.stopImmediatePropagation();showScheduleDetail(unpack(info.dataset.scheduleInfo));return}const nav=e.target.closest('[data-schedule-nav]');if(nav){e.stopImmediatePropagation();window.open(navUrl(unpack(nav.dataset.scheduleNav),'walk'),'_blank');return}const schedule=e.target.closest('[data-schedule-detail]');if(schedule&&!e.target.closest('button,a')){e.stopImmediatePropagation();showScheduleDetail(unpack(schedule.dataset.scheduleDetail));return}const action=e.target.closest('[data-card-action]');if(action?.dataset.cardAction==='activity-detail'){e.stopImmediatePropagation();showActivity();return}if(action?.dataset.cardAction==='activity-nav'){e.stopImmediatePropagation();window.open(navUrl({name:DB.activity.place,lat:30.5468,lon:114.4125},'walk'),'_blank');return}const card=e.target.closest('[data-activity-detail]');if(card&&!e.target.closest('button,a')){e.stopImmediatePropagation();showActivity()}});
document.addEventListener('click',e=>{if(e.target.closest('[data-action="back"]'))showScreen('home');if(e.target.closest('[data-action="new"]'))initChat();if(e.target.closest('[data-open-route]'))openRoute();if(e.target.closest('[data-action="route-back"]')){showScreen('chat');messages.scrollTop=routeState.chatScroll}if(e.target.closest('[data-action="save-route"]'))saveRoute();if(e.target.closest('[data-action="start-route"]'))window.open(navUrl({name:routeState.stops.at(-1),lat:30.5437,lon:114.4096},'walk'),'_blank');const mode=e.target.closest('[data-route-mode]');if(mode){routeState.mode=mode.dataset.routeMode;renderRoute()}if(e.target.closest('[data-action="add-stop"]')){routeState.stops.splice(-1,0,'楚天台');renderRoute()}const remove=e.target.closest('[data-remove-stop]');if(remove&&routeState.stops.length>2){routeState.stops.splice(+remove.dataset.removeStop,1);renderRoute()}if(e.target.closest('[data-action="generate-route"]')){routeState.stops=['磨山北门','咖啡烘焙市集','楚城码头','湖岸休息点','滑道广场舞台'];routeState.mode='official';renderRoute();toast('已结合偏好生成路线')}const place=e.target.closest('[data-place]');if(place)showPlace(unpack(place.dataset.place));const hi=e.target.closest('[data-highlight]');if(hi)showHighlight(+hi.dataset.highlight);const ext=e.target.closest('[data-external]');if(ext)confirmExternal(ext.dataset.external,ext.dataset.externalType);const drive=e.target.closest('[data-drive]');if(drive){const p=unpack(drive.dataset.drive);window.open(navUrl(p,'car'),'_blank')}const action=e.target.closest('[data-card-action]');if(action){if(action.dataset.cardAction==='schedule')ask('活动日程');else if(action.dataset.cardAction==='sos')toast('紧急求助演示：已携带当前位置');else if(action.dataset.cardAction==='sort-parking'){DB.parking.sort((a,b)=>b.spaces-a.spaces);action.closest('.parking-list').innerHTML=`<div class="parking-toolbar"><b>附近停车场</b><button data-card-action="sort-parking">已按余位排序</button></div>`+DB.parking.map((p,i)=>parkingHTML(p,i)).join('')}else toast('提醒已开启')}if(e.target===detailSheet||e.target.closest('[data-close]'))detailSheet.className='sheet'});initChat();renderRoute();renderScenarioList();
